"""The core agent loop: gather → act → verify → checkpoint."""

import json
from pathlib import Path

from lra.anchor import MissionAnchor, ChecklistItem
from lra.tools import ToolDispatcher
from lra.verify import DeterministicVerifier, VerificationResult


class AgentLoop:
    """Runs one cycle of gather → act → verify → checkpoint."""

    def __init__(
        self,
        anchor: MissionAnchor,
        tools: ToolDispatcher,
        verifier: DeterministicVerifier,
    ):
        self.anchor = anchor
        self.tools = tools
        self.verifier = verifier

    def gather(self, item: ChecklistItem) -> dict:
        progress = self.anchor.read_progress()
        checklist = self.anchor.read_checklist()
        return {
            "item": item,
            "progress": progress,
            "checklist": checklist,
        }

    def act(self, item: ChecklistItem, context: dict) -> dict:
        # Minimal deterministic stand-in for an LLM-driven act step.
        # In production this would call an LLM with tools.
        if "create hello.py" in item.description.lower():
            result = self.tools.dispatch("write_file", {
                "path": str(self.anchor.workdir / "hello.py"),
                "content": "# Auto-generated by LRA loop\nprint(\"Hello, durable world!\")\n",
            })
        elif "test" in item.description.lower() and item.id == "2":
            result = self.tools.dispatch("write_file", {
                "path": str(self.anchor.workdir / "tests" / "test_hello.py"),
                "content": "import hello\n\ndef test_hello_output(capsys):\n    hello.main()\n    captured = capsys.readouterr()\n    assert captured.out == "Hello, durable world!\n"\n",
            })
        else:
            result = {"ok": False, "error": "No implementation for this item"}

        self.anchor.log_event(action="act", item_id=item.id, result=result)
        return result

    def verify(self, item: ChecklistItem) -> VerificationResult:
        result = self.verifier.verify(workdir=str(self.anchor.workdir))
        self.anchor.log_event(
            action="verify",
            item_id=item.id,
            passed=result.all_passed,
            checks=[{"name": c.name, "passed": c.passed} for c in result.checks],
        )
        return result

    def checkpoint(self, item: ChecklistItem, result: VerificationResult) -> None:
        verified_by = [c.name for c in result.checks if c.passed]
        if result.all_passed:
            self.anchor.update_item(item.id, "done", verified_by=verified_by)
            self.anchor.write_progress(
                self.anchor.read_progress()
                + f"\n- ✅ Item {item.id}: {item.description}\n"
            )
        else:
            self.anchor.update_item(item.id, "blocked", verified_by=verified_by)
            self.anchor.write_progress(
                self.anchor.read_progress()
                + f"\n- ❌ Item {item.id}: {item.description} (blocked)\n"
            )
        self.anchor.log_event(
            action="checkpoint", item_id=item.id, status="done" if result.all_passed else "blocked"
        )

    def cycle(self, item: ChecklistItem | None = None) -> bool:
        if item is None:
            item = self.anchor.next_item()
        if item is None:
            return False
        self.anchor.update_item(item.id, "in_progress")
        context = self.gather(item)
        self.act(item, context)
        result = self.verify(item)
        self.checkpoint(item, result)
        return not result.all_passed
